name: warm-cache

on:
  push:
    branches:
      - main
  schedule:
    - cron: '37 3 */4 * *'
  workflow_dispatch:

jobs:
  cli:
    name: cargo-cli
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Restore cargo cache
        uses: actions/cache/restore@v4
        id: cargo-cache
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            src-tauri/target
          key: cargo-cli-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            cargo-cli-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-
            cargo-cli-${{ runner.os }}-
      - name: Fetch dependencies
        run: cargo fetch --manifest-path src-tauri/Cargo.toml
      - name: Save cargo cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            src-tauri/target
          key: cargo-cli-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}

  android:
    name: cargo-android
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
      - name: Restore cargo cache
        uses: actions/cache/restore@v4
        id: cargo-cache
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            src-tauri/target/aarch64-linux-android
          key: cargo-android-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            cargo-android-${{ hashFiles('**/Cargo.lock') }}-
            cargo-android-
      - name: Fetch dependencies
        run: cargo fetch --manifest-path src-tauri/Cargo.toml
      - name: Save cargo cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            src-tauri/target/aarch64-linux-android
          key: cargo-android-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
